
# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/vonzimmerman/displaycase/models/description/columns.yaml

# Model Class name
modelClass: Vonzimmerman\DisplayCase\Models\Description

# List Title
title: Manage Sections

# Link URL for each record
# recordUrl: october/test/posts/update/:id
recordOnClick: "$.popup({ handler: 'onUpdateForm', extraData: { section_mode: 1, record_id: ':id' } })"

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
