title: Items
modelClass: Vonzimmerman\DisplayCase\Models\Item
list: $/vonzimmerman/displaycase/models/item/columns.yaml
recordUrl: 'vonzimmerman/displaycase/items/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
