section:
    label: 'vonzimmerman.displaycase::lang.item.section'
    span: full
    manage:
      context: relation
      form: $/vonzimmerman/displaycase/models/section/fields.yaml
    defaultSort:
      column: sort_order
      direction: asc
    view:
      list: $/vonzimmerman/displaycase/models/section/columns.yaml
      toolbarButtons: create|delete|remove
