# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Items

# Attribute name
nameFrom: title

# Model Class name
modelClass: Vonzimmerman\DisplayCase\Models\Item

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
 
