list: $/vonzimmerman/displaycase/models/profile/columns.yaml
modelClass: Vonzimmerman\DisplayCase\Models\Profile
title: Profile
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'vonzimmerman/displaycase/profile/update/:id'
