links:
    label: 'vonzimmerman.displaycase::lang.link.link'
    span: full
    manage:
      context: relation
      form: $/vonzimmerman/displaycase/models/links/fields.yaml
    view:
      list: $/vonzimmerman/displaycase/models/links/columns.yaml
      toolbarButtons: create|delete|remove
