plugin:
    name: 'vonzimmerman.displaycase::lang.plugin.name'
    description: 'vonzimmerman.displaycase::lang.plugin.description'
    author: 'Paul & Robert Von Zimmerman'
    icon: oc-icon-adjust
    homepage: ''
permissions:
    showcase.manage_items:
        tab: 'vonzimmerman.displaycase::lang.plugin.name'
        label: 'vonzimmerman.displaycase::lang.item.manage_books'
navigation:
    main-menu-item:
        label: 'vonzimmerman.displaycase::lang.plugin.title'
        url: vonzimmerman/displaycase/items
        icon: icon-life-ring
        sideMenu:
            items:
                label: 'vonzimmerman.displaycase::lang.item.manage'
                url: vonzimmerman/displaycase/items
                icon: icon-film
            tags:
                label: 'vonzimmerman.displaycase::lang.item.tags'
                url: vonzimmerman/displaycase/tags
                icon: icon-tag
            profile:
                label: 'vonzimmerman.displaycase::lang.profile.profile'
                url: vonzimmerman/displaycase/profile
                icon: icon-user
