name: Description
form: $/vonzimmerman/displaycase/models/description/fields.yaml
modelClass: Vonzimmerman\DisplayCase\Models\Description
defaultRedirect: vonzimmerman/displaycase/description
create:
    redirect: 'vonzimmerman/displaycase/description/update/:id'
    redirectClose: vonzimmerman/displaycase/description
update:
    redirect: vonzimmerman/displaycase/description
    redirectClose: vonzimmerman/displaycase/description
