title: Showcase
modelClass: Paul\AgencyPages\Models\Item
list: $/paul/agencypages/models/item/columns.yaml
recordUrl: 'paul/agencypages/showcase/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
