name: Tags
form: $/vonzimmerman/displaycase/models/tags/fields.yaml
modelClass: Vonzimmerman\DisplayCase\Models\Tags
defaultRedirect: vonzimmerman/displaycase/tags
create:
    redirect: 'vonzimmerman/displaycase/tags/update/:id'
    redirectClose: vonzimmerman/displaycase/tags
update:
    redirect: vonzimmerman/displaycase/tags
    redirectClose: vonzimmerman/displaycase/tags
