list: $/paul/agencypages/models/tags/columns.yaml
modelClass: Paul\AgencyPages\Models\Tags
title: Tags
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'paul/agencypages/tags/update/:id'
